function plotTerminalSet(file)

% Authors:      Alexander Wischnewski
%
% Description:  
%   visualizes the intention behind the terminal set design
%
% Inputs: 
%   file: file with data generated by recoverScenario.m

% load data
load(file); 

% determine scale factor for terminal set
scale_terminal = be_l_abs(1)/v_traj(end); 

%% plot all the stuff
figure; grid on; hold on; box on; 
plot(v_traj); 
plot(v_traj.*scale_terminal); 
plot(vx_pred_log); 
plot(vx_pred, 'k'); 
plot(vx_pred(1:sys.N_hor) + ub_v', 'k--', 'HandleVisibility','off'); 
plot(vx_pred(1:sys.N_hor) + lb_v', 'k--', 'HandleVisibility','off'); 
xlabel('Discretization points'); 
ylabel('Velocity in mps'); 
legend('Target', 'Safe Target', 'MPC', 'TMPC'); 
matlab2tikz('TerminalSet_vel.tex', 'standalone', true);
xlim([1 51]); 

figure; grid on; hold on; box on; 
plot(abs(ax_pred_log/P_VDC_AxLim) + abs(ay_pred_log/P_VDC_AyLim)); 
plot(abs(ax_pred/P_VDC_AxLim) + abs(ay_pred/P_VDC_AyLim), 'k'); 
plot(abs(ax_pred/P_VDC_AxLim) + abs(ay_pred/P_VDC_AyLim) + ub_tire1', 'k--'); 
plot(abs(ax_pred/P_VDC_AxLim) + abs(ay_pred/P_VDC_AyLim) + lb_tire1', 'k--', 'HandleVisibility','off'); 
grid on; 
xlabel('Discretization points'); 
ylabel('Tire utilization'); 
legend('MPC', 'TMPC', 'Tube'); 
matlab2tikz('TerminalSet_acc.tex', 'standalone', true);
xlim([1 50]); 
ylim([0 1]); 

